### ISSUE TITLE
Exporting Config

### ISSUE THREAD

**Issue by cbarlow1993** [pixielabs/jsecrets#3]
Any suggestions how you might export a config which has async returned params?

For example exporting sequelize config for re-use in other files.

**Comment by jalada** [comment]
Hey @cbarlow1993 thanks for getting in touch! Apologies, I think this issue slipped through our notifications, we'll get back to you ASAP.

**Comment by JonathanAndrews** [comment]
Hi @cbarlow1993,
I'm not sure I really understand the question.
Would you be able to provide us with a bit more information?
