### ISSUE TITLE
How to use await without async function ?

### ISSUE THREAD

**Issue by sanket-work** [pixielabs/jsecrets#4]
The example shown in readme has used await without the async or any function.
When I try to do the same I get an error.

**Comment by JonathanAndrews** [comment]
Hi @sanket-work,
Yep, in order to use the `await` you will have to wrap it in an `async` function.
```js
(async () => {
  try {
    await jsecrets.fetch("eu-west-2", ["databaseSecret", "anotherSecret"]);

    app.get("/database", (req, res) =>
      res.send(jsecrets.get("databaseSecret", "database"))
    );

    app.get("/jwt_signing_key", (req, res) =>
      res.send(jsecrets.get("anotherSecret", "jwt_signing_key"))
    );

    app.listen(port, () =>
      console.log(`Example app listening on port ${port}!`)
    );
  } catch (e) {
    console.log(e.message);
  }
})();
```

The above code snippet is taken from the example app which can be found in the spec directory: https://github.com/pixielabs/jsecrets/blob/master/spec/exampleApp/app.js
